#this is my first Python program on GitHub
name = input("What is your name? ")
response = "Hi, " + name + " My name is Python! hssss"
print("")
print("")
print(response)
print("")
print("")
print("                 ~~~~~")
print("                /  @ @|")
print("               / ____~~~**")
print("              / /   ")
print("              | |")
print("              | |")
print("   ~~         |")
print("  // )        | |")
print(" //   )       | |")
print("//            / /")
print("||           / /")
print("||~~~~~~~~~~/ /")
print("~~~~~~~~~~~~~~")
